"""add subgroup group ownership

Revision ID: 3bc41875de94
Revises: 45a0c83a5d5f
Create Date: 2026-09-19 21:25:06.598020
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '3bc41875de94'
down_revision: Union[str, Sequence[str], None] = '45a0c83a5d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subgroups', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subgroups_group_id'), 'subgroups', ['group_id'], unique=False)
    op.create_foreign_key(
        'fk_subgroups_group_id_groups',
        'subgroups',
        'groups',
        ['group_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.execute(
        """
        UPDATE subgroups AS subgroup
        SET group_id = grouped.group_id
        FROM (
            SELECT subgroup_students.subgroup_id,
                   min(students.group_id) AS group_id
            FROM subgroup_students
            JOIN students
              ON students.id = subgroup_students.student_id
            GROUP BY subgroup_students.subgroup_id
            HAVING count(DISTINCT students.group_id) = 1
        ) AS grouped
        WHERE subgroup.id = grouped.subgroup_id
        """
    )
    op.create_unique_constraint(
        'uq_subgroup_set_number',
        'subgroups',
        ['subgroup_set_id', 'group_id', 'subgroup_number'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_subgroup_set_number',
        'subgroups',
        type_='unique',
    )
    op.drop_constraint(
        'fk_subgroups_group_id_groups',
        'subgroups',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_subgroups_group_id'), table_name='subgroups')
    op.drop_column('subgroups', 'group_id')
    # ### end Alembic commands ###
