"""align existing schema

Revision ID: 45a0c83a5d5f
Revises: 0001_baseline
Create Date: 2026-09-19 21:22:46.733621
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '45a0c83a5d5f'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_curricula_academic_period_id'), 'curricula', ['academic_period_id'], unique=False)
    op.create_index(op.f('ix_lesson_targets_lecture_part_id'), 'lesson_targets', ['lecture_part_id'], unique=False)
    op.create_index(op.f('ix_lesson_targets_subgroup_bundle_id'), 'lesson_targets', ['subgroup_bundle_id'], unique=False)
    op.create_index(op.f('ix_lesson_targets_teacher_assignment_id'), 'lesson_targets', ['teacher_assignment_id'], unique=False)
    op.drop_constraint(op.f('uq_schedule_item_version_lesson'), 'schedule_items', type_='unique')
    op.create_foreign_key(
        'fk_students_group_id_groups',
        'students',
        'groups',
        ['group_id'],
        ['id'],
    )
    op.create_index(op.f('ix_subgroups_subgroup_set_id'), 'subgroups', ['subgroup_set_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignment_targets_lecture_part_id'), 'teacher_assignment_targets', ['lecture_part_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_lecture_part_id'), 'teacher_assignments', ['lecture_part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_assignments_lecture_part_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignment_targets_lecture_part_id'), table_name='teacher_assignment_targets')
    op.drop_index(op.f('ix_subgroups_subgroup_set_id'), table_name='subgroups')
    op.drop_constraint(
        'fk_students_group_id_groups',
        'students',
        type_='foreignkey',
    )
    op.create_unique_constraint(op.f('uq_schedule_item_version_lesson'), 'schedule_items', ['schedule_version_id', 'lesson_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_lesson_targets_teacher_assignment_id'), table_name='lesson_targets')
    op.drop_index(op.f('ix_lesson_targets_subgroup_bundle_id'), table_name='lesson_targets')
    op.drop_index(op.f('ix_lesson_targets_lecture_part_id'), table_name='lesson_targets')
    op.drop_index(op.f('ix_curricula_academic_period_id'), table_name='curricula')
    # ### end Alembic commands ###
